### ISSUE TITLE
world scanner error

### ISSUE THREAD

**Issue by shenjackyuanjie** [JsMacros/JsMacros#100]
```
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: Cannot invoke "net.minecraft.class_2826.method_12261()" because "section" is null
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at xyz.wagyourtail.jsmacros.client.api.classes.worldscanner.WorldScanner.streamChunkSections(WorldScanner.java:243)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at xyz.wagyourtail.jsmacros.client.api.classes.worldscanner.WorldScanner.scanChunkInternal(WorldScanner.java:127)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at xyz.wagyourtail.jsmacros.client.api.classes.worldscanner.WorldScanner.scanChunksInternal(WorldScanner.java:114)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at xyz.wagyourtail.jsmacros.client.api.classes.worldscanner.WorldScanner.scanChunkRange(WorldScanner.java:109)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at xyz.wagyourtail.jsmacros.client.api.classes.worldscanner.WorldScanner.scanAroundPlayer(WorldScanner.java:91)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at <js> :program(try.js:4:123-155)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at org.graalvm.polyglot.Context.eval(Context.java:379)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at xyz.wagyourtail.jsmacros.js.language.impl.GraalLanguageDefinition.exec(GraalLanguageDefinition.java:78)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at xyz.wagyourtail.jsmacros.core.language.BaseLanguage.lambda$trigger$1(BaseLanguage.java:49)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:00:09] [Script:{"trigger":"KEY_RISING", "event":"key.keyboard.v", "file":"farm\try.js"}/INFO]: [STDERR]: Caused by host exception: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2826.method_12261()" because "section" is null
```
```js

    let farm_seacher = World.getWorldScanner().withStringBlockFilter().contains("farmland").build();

    for(block in farm_seacher.scanAroundPlayer(10)) {
        Chat.log(block)
    }
```

**Comment by shenjackyuanjie** [comment]
fixed in https://github.com/JsMacros/JsMacros/commit/98ff3093525abb8077b12a9d8367b34906319d36
need a release
