### ISSUE TITLE
Some AMD CPU's lag on script starts (possible mitigation)

### ISSUE THREAD

**Issue by wagyourtail** [JsMacros/JsMacros#85]
Thread.start() takes longer than expected on certain AMD CPU's, which can cause significant fps lag as scripts start the thread on the main minecraft thread (this is also true of `JavaWrapper.methodToJavaAsync` and `JsMacros.on`).

if you are experiencing this issue, please test if https://github.com/JsMacros/JsMacros/actions/runs/4111856428 fixes/alleviates the problem, if not, I need to look further into it... either way post here so I know someone with this issue has tested this solution

![visualvm 1](https://i.imgur.com/GRDR3HZ.jpg)
![visualvm 2](https://cdn.discordapp.com/attachments/739655736296210442/1062274687205380116/image.png)

**Comment by CyrenArkade** [comment]
Dunno if I'm doing something wrong, this is what happens. Copied from the log.
```
org.graalvm.polyglot.PolyglotException: java.lang.NoClassDefFoundError: Could not initialize class com.oracle.truffle.js.lang.JavaScriptLanguage
	at com.oracle.truffle.js.lang.JavaScriptLanguageProvider.create(JavaScriptLanguageProvider.java:51)
	at com.oracle.truffle.polyglot.LanguageCache.loadLanguage(LanguageCache.java:548)
	at com.oracle.truffle.polyglot.PolyglotLanguageInstance.<init>(PolyglotLanguageInstance.java:100)
	at com.oracle.truffle.polyglot.PolyglotLanguage.getInitLanguage(PolyglotLanguage.java:152)
	at com.oracle.truffle.polyglot.PolyglotLanguage.ensureInitialized(PolyglotLanguage.java:142)
	at com.oracle.truffle.polyglot.PolyglotLanguage.getOptionsInternal(PolyglotLanguage.java:134)
	at com.oracle.truffle.polyglot.PolyglotLanguage.getOptionValues(PolyglotLanguage.java:202)
	at com.oracle.truffle.polyglot.PolyglotContextConfig.<init>(PolyglotContextConfig.java:266)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.createContext(PolyglotEngineImpl.java:1697)
	at com.oracle.truffle.polyglot.PolyglotEngineDispatch.createContext(PolyglotEngineDispatch.java:159)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1837)
	at xyz.wagyourtail.jsmacros.js.language.impl.GraalLanguageDefinition.buildContext(GraalLanguageDefinition.java:56)
	at xyz.wagyourtail.jsmacros.js.language.impl.GraalLanguageDefinition.exec(GraalLanguageDefinition.java:89)
	at TRANSFORMER/jsmacros@1.8.4-beta-e3c3826/xyz.wagyourtail.jsmacros.core.language.BaseLanguage.lambda$trigger$1(BaseLanguage.java:54)
	at TRANSFORMER/jsmacros@1.8.4-beta-e3c3826/xyz.wagyourtail.jsmacros.core.threads.JsMacrosThreadPool$PoolThread.run(JsMacrosThreadPool.java:78)
Caused by: Attached Guest Language Frames (0)
Internal GraalVM error, please report at https://github.com/oracle/graal/issues/.
java.lang.RuntimeException: java.lang.NullPointerException
	at xyz.wagyourtail.jsmacros.js.ValueAccessor.getReceiver(ValueAccessor.java:17)
	at xyz.wagyourtail.jsmacros.js.language.impl.GuestExceptionSimplifier.simplifyException(GuestExceptionSimplifier.java:41)
	at xyz.wagyourtail.jsmacros.js.GraalExtension.wrapException(GraalExtension.java:111)
	at TRANSFORMER/jsmacros@1.8.4-beta-e3c3826/xyz.wagyourtail.jsmacros.core.Core.wrapException(Core.java:164)
	at TRANSFORMER/jsmacros@1.8.4-beta-e3c3826/xyz.wagyourtail.jsmacros.client.config.Profile.logError(Profile.java:115)
	at TRANSFORMER/jsmacros@1.8.4-beta-e3c3826/xyz.wagyourtail.jsmacros.core.language.BaseLanguage.lambda$trigger$1(BaseLanguage.java:74)
	at TRANSFORMER/jsmacros@1.8.4-beta-e3c3826/xyz.wagyourtail.jsmacros.core.threads.JsMacrosThreadPool$PoolThread.run(JsMacrosThreadPool.java:78)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.lang.invoke.DirectMethodHandle.checkBase(DirectMethodHandle.java:566)
	at xyz.wagyourtail.jsmacros.js.ValueAccessor.getReceiver(ValueAccessor.java:15)
	... 6 more
```
