### ISSUE TITLE
[1.12.2] MixinScreen onScroll crash

### ISSUE THREAD

**Issue by FYWinds** [JsMacros/JsMacros#96]
After the commit 99c650c6ebee065c3d8d34edb2bc083cd78118ce and a859f4e2f99753042e434883b7580616dfc63343, the mod will crash in multiple cases, whether Optifine is installed or not.

### If Optifine not installed
As far as I get from the project readme, I didn't find any hard requirement of Optifine to be installed.
This will result in the mixin of `GuiScreen` fail, and crash the game during initialization.
```log
org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect$onRender$zzc000(Lnet/minecraft/client/gui/GuiScreen;IIF)V in jsmacros.mixins.json:access.MixinGameRenderer failed injection check, (0/1) succeeded. Using refmap jsmacros-1.12.2-common-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1203)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:938)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:322)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

### If Optifine installed
When trying to scroll in ANY Screens, such as chat log or modlist, it will also result in a crash.
```log
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1772) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_341]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_341]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_341]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_341]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.AbstractMethodError: Method net/minecraftforge/fml/client/GuiModList.jsmacros_mouseScrolled(III)V is abstract
	at net.minecraftforge.fml.client.GuiModList.jsmacros_mouseScrolled(GuiModList.java)
	at net.minecraft.client.gui.GuiScreen.handler$onMouseScrolled$zzg000(GuiScreen.java:1279)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:522)
	at net.minecraftforge.fml.client.GuiModList.func_146274_d(GuiModList.java:329)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by wagyourtail** [comment]
I fixed for 1.8.9 after https://github.com/JsMacros/JsMacros/commit/43099514fc6df4c6f0e9d05e011b3f93d1d8ed7f i guess i missed 1.12 will copy to there

**Comment by FYWinds** [comment]
Thanks for your immediately reply! since this has already been fixed, I'll close this issue.

**Comment by wagyourtail** [comment]
when this finishes building, can you check to make sure https://github.com/JsMacros/JsMacros/actions/runs/4711224763 fixes it

**Comment by FYWinds** [comment]
It seems that the build failed with an completely unrelated reason.
```log
/home/runner/work/JsMacros/JsMacros/common/src/main/java/xyz/wagyourtail/jsmacros/client/mixins/access/MixinMouse.java:39: warning: Unable to locate method mapping for @At(INVOKE.<target>) 'Lorg/lwjgl/input/Mouse;getEventButton()I'

> Task :common:compileJava
    @Inject(method = "handleMouse", at = @At(value = "INVOKE", target = "Lorg/lwjgl/input/Mouse;getEventButton()I"), locals = LocalCapture.CAPTURE_FAILHARD)
    ^
/home/runner/work/JsMacros/JsMacros/common/src/main/java/xyz/wagyourtail/jsmacros/client/access/IScreenInternal.java:20: error: cannot find symbol
    GuiButton getFocused();
    ^
  symbol:   class GuiButton
  location: interface IScreenInternal
  ```
  
  Also, my local fix removing the duplicate mouseScrolled failed the build in the same step.

**Comment by wagyourtail** [comment]
yeah, I noticed https://github.com/JsMacros/JsMacros/actions/runs/4711254632

**Comment by FYWinds** [comment]
The problem is solved.
